import Link from 'next/link'
import '../styles/global.module.scss'
import { JetBrains_Mono } from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const jetbrains = JetBrains_Mono({
  weight: ['300', '400', '500'],
  style: ['italic', 'normal'],
  subsets: ['latin']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`body ${jetbrains.className}`}>
        <Link className='text' href='/about'>about</Link>
        <Link className='text' href='/projects'>projects</Link>
        {children}
      </body>
    </html>
  )
}
