import '@st/globals.scss';
import '@st/defaults.scss';
import { JetBrains_Mono } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const jetbrains = JetBrains_Mono({
  weight: ['300', '400', '500'],
  style: ['italic', 'normal'],
  subsets: ['latin']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jetbrains.className}`}>
        <div className='screen'>
          <Navbar />
          <div className='screen__current'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
